DarkPlasma_OrderIdAlias:
  name: DarkPlasma_OrderIdAlias
  version: '1.0.0'
  year: 2020
  license: MIT
  histories:
    - date: '2020/08/27'
      version: '1.0.0'
      description: 'MZ版公開'

  locates:
    - ja
  plugindesc:
    ja: 'スキル/アイテムの表示順序IDを書き換える'
  parameters: []
  commands: []
  structures:
  help:
    ja: |
      アイテムまたはスキルの順序がID順の場合、メモ欄に以下のように記述することで、
      IDの代わりにその数値を順序として使います。

      <OrderId:xxx> xxxは整数値
