DarkPlasma_ForceFormation:
  name: DarkPlasma_ForceFormation
  version: '1.0.0'
  year: 2020
  license: MIT
  histories:
    - date: '2020/08/28'
      version: '1.0.0'
      description: 'MZ版公開'

  locates:
    - ja
  plugindesc:
    ja: '全滅時に後衛と強制的に入れ替える'
  parameters:
    - param: forceFormationMessage
      text:
        ja: 強制入れ替えのメッセージ
      desc:
        ja: 強制的に入れ替える際のメッセージ
      type: string
      default: 倒れた前衛に代わって後衛が戦闘に加わった！
    - param: forceFormationCommonEvent
      text:
        ja: 強制入れ替え時のコモンイベント
      desc:
        ja: 強制的に入れ替える際に実行するコモンイベントID
      default: 0
      type: common_event
    - param: forceTurnChange
      text:
        ja: 強制入れ替え時に次ターンへ
      desc:
        ja: 強制的に入れ替える際に次のターンへ移行する
      type: boolean
      default: false
  commands: []
  structures:
  help:
    ja: |
      戦闘時 前衛が全滅したら強制的に後衛と入れ替えます。
