DarkPlasma_WaitForCloseChoiceList:
  name: DarkPlasma_WaitForCloseChioceList
  version: '1.0.0'
  year: 2020
  license: MIT
  histories:
    - date: '2020/08/05'
      version: '1.0.0'
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'シーンチェンジの際に選択肢ウィンドウが閉じるのを待つ'
  parameters: []
  help:
    ja: |
      RPGツクールMZでは選択肢ウィンドウの選択肢が多数ある場合、
      新しいシーンのウィンドウの背後に選択肢ウィンドウの残骸が残ります。

      本プラグインではシーンチェンジの際に選択肢ウィンドウが閉じきる前に
      別シーンのウィンドウが開いてしまうのを防ぎます。
