DarkPlasma_ExpandTargetScope:
  name: DarkPlasma_ExpandTargetScope
  version: '1.0.0'
  year: 2020
  license: MIT
  histories:
    - date: '2020/09/05'
      version: '1.0.0'
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'スキル/アイテムの対象全体化'
  parameters:
    - param: switchScopeButton
      text:
        ja: 全体化ボタン
      default: shift
      type: select
      options:
        - name: pageup
        - name: pagedown
        - name: shift
        - name: control
        - name: tab
    - param: damageRateForAll
      text:
        ja: 全体ダメージ倍率
      type: number
      default: 70
      desc:
        ja: 全体化時のダメージ倍率（％）
    - param: mpCostRateForAll
      text:
        ja: 全体MP倍率
      type: number
      default: 100
      desc:
        ja: 全体化時のMP消費倍率（％）
  help:
    ja: |
      対象が単体のスキルやアイテムのメモ欄に以下のように記述することで、
      戦闘中に対象を全体化できるようになります。
      <canExpandScope>

      以下のように記述すると、全体化時のアニメーションが n に差し替えられます。
      <expandedAnimationId:n>
