DarkPlasma_ClearEquip:
  name: DarkPlasma_ClearEquip
  version: '2.0.2'
  year: 2020
  license: MIT
  histories:
    - date: '2020/10/10'
      version: '2.0.2'
      description: 'リファクタ'
    - date: '2020/09/29'
      version: '2.0.1'
      description: 'プラグインコマンドに説明を追加'
    - date: '2020/09/08'
      version: '2.0.0'
      description: 'パラメータ名を変更'
    - date: '2020/08/27'
      version: '1.0.0'
      description: 'MZ版公開'

  locates:
    - ja
  plugindesc:
    ja: '装備をすべてはずす'
  parameters:
    - param: clearEquipWhenMemberIsOut
      text:
        ja: パーティアウト時装備はずす
      desc:
        ja: パーティから外れたときに装備をすべてはずすかどうか
      type: boolean
      default: false
  commands:
    - command: clearEquip
      text:
        ja: アクターの装備をすべてはずす
      desc:
        ja: 指定したアクターの装備をすべてはずします。
      args:
        - arg: actorId
          text:
            ja: アクター
          type: actor
  structures:
  help:
    ja: |
      プラグインパラメータの設定をONにしておくと、パーティからメンバーがはずれたとき、
      そのメンバーの装備をすべてはずします。

      プラグインコマンド: アクターの装備をすべてはずす を提供します。
